name: CI
on: [pull_request, push, workflow_call, workflow_dispatch]
jobs:
  format:
    uses: ./.github/workflows/format.yml
  lint:
    uses: ./.github/workflows/lint.yml
  document:
    uses: ./.github/workflows/document.yml
  test:
    needs: [document, format, lint]
    uses: ./.github/workflows/test.yml
