name: Feature Powerset
on: [pull_request, workflow_call]
jobs:
  powerset:
    name: Feature Powerset
    env:
      RUSTFLAGS: -D warnings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack
      - run: cargo hack check --tests --feature-powerset
