name: Feature Powerset
on: [workflow_call, workflow_dispatch]
jobs:
  powerset:
    name: Feature Powerset
    env:
      RUSTFLAGS: -D warnings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack
      - run: cargo hack check --tests --feature-powerset --skip default
